/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "i2c_lcd.h"


int main(void)
{
	int count=0;
	//char str[32];
	SystemInit();
	Lcd_Init();
//	ret = Lcd_Init();

		Lcd_Puts(LCD_FN_SET_4BIT_1LINES, "Bhimashankar");
		while(1){
		for(count = 1; count < 13; count++) {
			//sprintf(str, "God Bless You %d", count);
			//Lcd_Puts(LCD_LINE2, str);
			Lcd_Shiftleft();
			DelayMs(500);
		}
}

	return 0;
}

