/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include<string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[32];
	int choice;

	SystemInit();
	UartInit(9600);
do{
	UartPuts("0.exit\r\n1. Red Led On\r\n2. green Led Off\r\n3. Blue orange On\r\n4. Blue Led Off");
	//UartPutint(a);
	UartGets(str);
	sscanf(str,"%d",&choice);


	switch(choice) {

	case 1:UartPuts("1 hello");LedBlink(LED_RED_PIN, 1000);break;
	case 2:UartPuts("2 hello");LedBlink(LED_GREEN_PIN, 1000);break;
	case 3:UartPuts("3 hello");LedBlink(LED_ORANGE_PIN, 1000);break;
	case 4:UartPuts("4 hello");LedBlink(LED_BLUE_PIN, 1000);break;
	}

    }while(choice!=0);
return 0;
}





